name: Build docker image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to build and push with"
        required: true
        default: "latest"
  workflow_call:
    inputs:
      tag:
        type: string
        required: true
        default: "latest"

jobs:
  build_and_push_docker_image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if build related changes were made
        id: check
        uses: dorny/paths-filter@v2
        with:
          filters: |
            build:
              - 'ci/scripts/docker.sh"
              - 'ci/docker/**'
              - '.github/workflows/build_docker.yml'

      - name: Setup environment variables related to the docker image
        run: |
          echo "DOCKER_IMAGE=ghcr.io/${{ github.repository }}" >> $GITHUB_ENV
          echo "DOCKER_TAG=${{ github.event.inputs.tag }}" >> $GITHUB_ENV

      - name: Print info about the job being triggered
        run: |
          echo "DOCKER_IMAGE=${{ env.DOCKER_IMAGE }}"
          echo "DOCKER_TAG=${{ env.DOCKER_TAG }}"

      - name: Build and push Docker images
        run: >
          ./ci/scripts/docker.sh
          build_push
          ./ci/docker/Dockerfile.base
          ${{ env.DOCKER_IMAGE }}
          ${{ env.DOCKER_TAG }}
