name: Build docker image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to build and push with"
        required: true
        default: "latest"
  workflow_call:
    inputs:
      tag:
        type: string
        required: true
        default: "latest"
    outputs:
      image:
        description: "The docker image that was generated"
        value: ${{ jobs.build_and_push_docker_image.outputs.image }}
      tag:
        description: "The tag that the docker image was pushed with"
        value: ${{ jobs.build_and_push_docker_image.outputs.tag }}

jobs:
  build_and_push_docker_image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    outputs:
      image: ${{ steps.setup_output.outputs.docker_image }}
      tag: ${{ steps.setup_output.outputs.docker_tag }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if build related changes were made
        id: check
        uses: dorny/paths-filter@v2
        with:
          filters: |
            build:
              - 'ci/scripts/docker.sh'
              - 'ci/docker/**'
              - '.github/workflows/build_docker.yml'

      - name: Setup environment variables related to the docker image
        id: setup_output
        run: |
          echo "docker_image=ghcr.io/${{ github.repository }}" >> $GITHUB_OUTPUT
          echo "docker_tag=${{ steps.check.outputs.build != 'true' && 'latest' || inputs.tag }}" >> $GITHUB_OUTPUT

      - name: Print info about the job being triggered
        run: |
          echo "Building and deploying the docker image:"
          echo "  docker_image=${{ steps.setup_output.outputs.docker_image }}"
          echo "  docker_tag=${{ steps.setup_output.outputs.docker_tag }}"

      - name: Print the reason for skipping the job
        if: steps.check.outputs.build != 'true'
        run: |
          echo "Skipping the job because no build related changes were made."

      - name: Build and push Docker images
        if: steps.check.outputs.build == 'true'
        run: >
          ./ci/scripts/docker_build_push.sh
          ./ci/docker/Dockerfile.base
          ${{ steps.setup_output.outputs.docker_image }}
          ${{ steps.setup_output.outputs.docker_tag }}
