name: Build and test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Configure
        run: >
          cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON

      - name: Build
        run: >
          cmake --build build -j

  test:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: ghcr.io/${{ github.repository }}:latest
    steps:
      - name: Test
        run: >
          export DISPLAY=:1
          Xvfb :1 -screen 0 1024x768x24 &
          ctest --output-on-failure -j --test-dir build

  publish:
    runs-on: ubuntu-latest
    needs: test
    container:
      image: ghcr.io/${{ github.repository }}:latest
    steps:
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: linux-build
          path: build
