name: Build and test

on:
  workflow_call:
    inputs:
      image:
        type: string
        required: true
      tag:
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image }}:${{ inputs.tag }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Configure
        run: |
          set -e
          cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON

      - name: Build
        run: |
          set -e
          cmake --build build -j

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-build
          path: build

  test:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: ghcr.io/${{ github.repository }}:latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: linux-build
          path: build

      - name: Test
        run: |
          set -e
          cd build
          export DISPLAY=:1
          Xvfb :1 -screen 0 1024x768x24 &
          ctest --output-on-failure -j
