name: Build docker image

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
    # secrets:
    #   envPAT:
    #     required: true

jobs:
  build_and_push_docker_image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        run: >
          ./ci/scripts/docker.sh
          build_push
          ./ci/docker/Dockerfile.base
          ghcr.io/${{ github.repository }}
          ${{ github.event.inputs.tag }}
