name: Delete docker images

on:
  pull_request:
    types: [closed]

jobs:
  delete_docker_image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        if: steps.docker_image_update.outputs.src == 'true'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        if: steps.docker_image_update.outputs.src == 'true'
        run: ./ci/scripts/docker_tag.sh

      - name: Build and push Docker images
        if: steps.docker_image_update.outputs.src == 'true'
        run: >
          ./ci/scripts/build.sh \
            delete \
            ghcr.io/${{ github.repository }} \
            ${{ steps.meta.outputs.tag }}
