name: Build docker images

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2.11.1
        id: docker_image_update
        with:
          filters: |
            src:
              - 'ci/docker/**'
              - '.github/workflows/docker-image-build-push.yml'

      - name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        if: steps.docker_image_update.outputs.src == 'true'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        if: steps.docker_image_update.outputs.src == 'true'
        run: ./ci/scripts/docker_tag.sh

      - name: Build and push Docker images
        if: steps.docker_image_update.outputs.src == 'true'
        run: >
          ./ci/scripts/docker.sh \
            build_push \
            ./ci/docker/Dockerfile.base \
            ghcr.io/${{ github.repository }} \
            ${{ steps.meta.outputs.tag }}
