name: Trigger the CI workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trigger_docker_build:
    uses: "./.github/workflows/build_docker.yml"
    with:
      tag: "latest"

  trigger_builds:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger the build workflow
        uses: './.github/workflows/build_linux.yml'
