name: Trigger the CI workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trigger_docker_build:
    uses: "./.github/workflows/build_docker.yml"

  print_docker_info:
    needs: trigger-docker-build
    runs-on: ubuntu-latest
    steps:
      - name: Print info about the job being triggered
        run: |
          echo "DOCKER_IMAGE=${{ env.DOCKER_IMAGE }}"
          echo "DOCKER_TAG=${{ env.DOCKER_TAG }}"

  # trigger-builds:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check if build related changes were made
  #       id: check
  #       uses: dorny/paths-filter@v2
  #       with:
  #         filters: |
  #           build:
  #             - 'ci/scripts/**'
  #             - 'ci/docker/**'
  #             - '.github/workflows/build_linux.yml'

  #     - name: Trigger the build workflow
  #       if: steps.check.outputs.build == 'true'
  #       uses: '.github/workflows/build_linux.yml'
